// Generates src/app/shared/icon/icon-paths.ts from Material Symbols (Outlined, weight 400, Apache-2.0).
// The app renders icons as inline SVG paths: no icon font to download, nothing to cache, works offline.
//
//   node scripts/generate-icons.mjs                 # fetches the SVGs from jsDelivr
//   ICONS_DIR=path/to/outlined node scripts/generate-icons.mjs   # or reads an extracted @material-symbols/svg-400
//
// Add a name to ICONS (a "-fill" suffix selects the filled variant), rerun, and commit the generated file.
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const VERSION = '0.47.5';
const ICONS = [
  'account_balance',
  'account_balance_wallet',
  'account_balance_wallet-fill',
  'account_circle',
  'add',
  'arrow_back',
  'bar_chart',
  'block',
  'bolt',
  'bolt-fill',
  'calendar_month',
  'candlestick_chart',
  'calendar_month-fill',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'cloud_off',
  'contrast',
  'dark_mode',
  'delete',
  'edit_note',
  'error',
  'event',
  'history',
  'how_to_vote',
  'info',
  'key',
  'keyboard_arrow_down',
  'light_mode',
  'link_off',
  'lock',
  'logout',
  'mail',
  'mark_email_read',
  'more_vert',
  'notifications',
  'open_in_new',
  'payments',
  'receipt_long',
  'refresh',
  'savings',
  'schedule',
  'search',
  'search_off',
  'send',
  'settings',
  'show_chart',
  'sort',
  'straighten',
  'swap_vert',
  'sync',
  'trending_down',
  'trending_up',
  'settings-fill',
  'star',
  'star-fill',
  'tune',
  'visibility',
  'visibility_off',
  'warning',
  'work',
];

async function load(name) {
  if (process.env.ICONS_DIR) return readFile(join(process.env.ICONS_DIR, `${name}.svg`), 'utf8');
  const url = `https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@${VERSION}/outlined/${name}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status} from ${url}`);
  return res.text();
}

const entries = [];
for (const name of ICONS) {
  const svg = await load(name);
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${name}: expected one <path>, found ${paths.length}`);
  entries.push(`  '${name}': '${paths[0]}',`);
}

const out = `// Generated by scripts/generate-icons.mjs from Material Symbols Outlined ${VERSION} (Apache-2.0). Do not edit.
// Each value is the single path of a 960×960 icon drawn in viewBox "0 -960 960 960".
export const ICON_PATHS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;
await writeFile(new URL('../src/app/shared/icon/icon-paths.ts', import.meta.url), out);
console.log(`Wrote ${ICONS.length} icons.`);
